version: '3'

services:
  automator:
    hostname: "automator"
    image: "automator:latest"
    networks:
      default:
    tty: true
    volumes:
      - /vagrant_data:/vagrant_data

networks:
  default:
    external:
      name: oob-automation