---
- name: Run commands on site_a_gateway and set the base IP config
  hosts: clab-IPSEC-VPN-site_a_gateway
  gather_facts: false

  tasks:
    - name: Configure clab-IPSEC-VPN-site_a_gateway
      arista.eos.eos_command:
        commands:
          - "enable"
          - "configure terminal"
          - "interface Ethernet1"
          - "   no switchport"
          - "   ip address 192.168.1.1/24"
          - "interface Ethernet2"
          - "   no switchport"
          - "   ip address 100.64.1.1/30"
          - "ip routing"

- name: Run commands on site_b_gateway and set the base IP config
  hosts: clab-IPSEC-VPN-site_b_gateway
  gather_facts: false

  tasks:
    - name: Configure clab-IPSEC-VPN-site_b_gateway
      arista.eos.eos_command:
        commands:
          - "enable"
          - "configure terminal"
          - "interface Ethernet1"
          - "   no switchport"
          - "   ip address 192.168.2.1/24"
          - "interface Ethernet2"
          - "   no switchport"
          - "   ip address 100.64.1.2/30"
          - "ip routing"

- name: Run commands on site_a_gateway and verify that both site_a_client and site_b_gateway are not reachable
  hosts: clab-IPSEC-VPN-site_a_gateway
  gather_facts: false

  tasks:
    - name: Ping site_b_gateway
      eos_command:
        commands: "ping 100.64.1.2"
      register: ip_reachability_state

    - name: Verfify that site_b_client is reachable
      assert:
        that:
          - ip_reachability_state.stdout[0] | regex_search('[1-5] received')  # A default ping request on arista sends 5 pings, thus we verify that a least 1 ping of of 5 has been received
        success_msg: "Ping test successful - A least one ping reply has been received"
        fail_msg: "Ping test failed - please verify manually"