---
- name: Run commands on remote LAB devices
  hosts: lab
  gather_facts: false

  tasks:
    - name: Configure device hostname from lines
      arista.eos.eos_command:
        commands:
          - "enable"
          - "configure terminal"
          - "hostname {{inventory_hostname}}-automation"
          - "ntp server 1.1.1.1"
          - "vlan 1001"
          - "   name 1001-LTD-Transfer"
          - "vlan 1002"
          - "   name 1002-LTD-HA"
          - "vlan 1003"
          - "   name 1003-LTD-Transfer"
          - "vlan 1004"
          - "   name 1004-LTD-Transfer"
          - "vlan 1005"
          - "   name 1005-LTD-Transfer"