version: '3'

services:
  ceos-1:
    hostname: CEOS-1
    image: "ceosimage:latest"
    command: /sbin/init
    privileged: true
    environment:
      container: docker
      CEOS: 1
      EOS_PLATFORM: ceoslab
      SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT: 1
      ETBA: 1
      INTFTYPE: eth
    networks:
      default:
      p2p:
  ceos-2:
    hostname: CEOS-2
    image: "ceosimage:latest"
    command: /sbin/init
    privileged: true
    environment:
      container: docker
      CEOS: 1
      EOS_PLATFORM: ceoslab
      SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT: 1
      ETBA: 1
      INTFTYPE: eth
    networks:
      default:
      p2p:

networks:
  default:
    external:
      name: oob-automation
  p2p:
