# Data Model for one IPSEC Site-to-site VPN Service
# ---
# Service Information
# ---
# customer_name: The customer name in an abreviated form (uppercase, between 3 and 6 caracter)
# change_request: A unique ID for the IPSEC VPN service
# provider_managed: When set to true, Ansible will generate the configuration for the corresponding site. When set to false, no configuration will be generated
# psk: The Pre-Shared Secret, never save in in clear test in production
customer_name: TEST
change_request: 123456789

provider_managed:
  site_a: true
  site_b: true

# Technical Information
# ---
# Most of the parameters should be self explaining, the only exotic one being:  
# universal_tunnel: When set to true, the VPN will only have one SA with 0.0.0.0/0 as traffic selector. Can be used for specific route-based VPNs.  
psk: uqgdsbiugUFQUZG7

p1:
  ike_version: 1
  dh_group: 2
  encryption: aes128
  integrity: sha1
  renegociation_time: 86400
  adressive_mode: false

p2:
  pfs: true
  dh_group: 2
  encryption: aes128
  integrity: sha1
  renegociation_time: 3600
  universal_tunnel: false
  site_a_networks:
    - 192.168.1.0/24
  site_b_networks:
    - 192.168.2.0/24